### ISSUE TITLE
Xiomi phone, your camera doesn't support generic capture

### ISSUE THREAD

**Issue by codenoid** [Sija/gphoto2.cr#31]
i do 

```
gphoto2 --summary --debug --debug-logfile=logfile.txt
```

![xcam1](https://user-images.githubusercontent.com/14269809/34821701-3287ae1a-f6f7-11e7-9bb4-0ecc5a80ad0d.png)

logfile.txt 
[logfile.txt](https://github.com/Sija/gphoto2.cr/files/1622214/logfile.txt)

**Comment by codenoid** [comment]
is gphoto2 doesn't support my Xiaomi Phone ?

**Comment by codenoid** [comment]
[my-logfile.txt](https://github.com/Sija/gphoto2.cr/files/1622238/my-logfile.txt)

**Comment by codenoid** [comment]
i see `Device Capabilities:`

**Comment by codenoid** [comment]
@Sija what camera are you using?

**Comment by Sija** [comment]
List of supported devices can be found [here](http://gphoto.org/proj/libgphoto2/support.php) or [here](https://github.com/gphoto/libgphoto2/blob/master/camlibs/ptp2/library.c#L608-L2183).

I'm using mostly Canon cameras: 40D, 550D, 600D.
